[package]
name = "mocklibc"
version = "0.1.0"
edition = "2021"
authors = ["Zoneshiyi <Zoneshiyi@163.com>"]

[lib]
name = "mocklibc"
crate-type = ["staticlib", "cdylib"]

[profile.release]
panic = "abort"

[dependencies]
